Remove all vim packages for CVE-2021-3872
ansible/galaxy_ng pull request #1085
Opened 2021-12-16 20:57 UTC by jctanner

Issue: AAH-1042

Signed-off-by: James Tanner <tanner.jc@gmail.com>

2021-12-17 16:33 UTC, awcrosby requested changes

2021-12-17 16:33 UTC, awcrosby commented on CHANGES/1042.cve
> +remove vim per CVE-2021-3872
Regarding `.cve` we have been using these file extensions per https://pypi.org/project/towncrier/, ci should be updated to fail on this
```
    .feature: Signifying a new feature.
    .bugfix: Signifying a bug fix.
    .doc: Signifying a documentation improvement.
    .removal: Signifying a deprecation or removal of public API.
    .misc: A ticket has been closed, but it is not of interest to users.
```

2021-12-17 20:48 UTC, drodowic approved these changes
/lgtm

2021-12-21 14:52 UTC, awcrosby commented on CHANGES/1042.misc
> +remove vim per CVE-2021-3872
This can be the same title as the PR.

FYI for .misc, the towncrier changelog lists only the link to the issue and not the text in the file, so this can be empty if desired (it should pass CI that way).

2021-12-21 15:47 UTC, awcrosby approved these changes

2021-12-21 17:13 UTC, merged