Skip checking commit messages from dependabot (ui repo)
ansible/galaxy_ng pull request #1088
Opened 2021-12-20 15:14 UTC by jctanner

Issue: AAH-1106

Signed-off-by: James Tanner <tanner.jc@gmail.com>

2021-12-20 15:42 UTC, rochacbruno requested changes
There are some files on the CI that we can't change directly, we need to make changes on template_condig.yml or to template repo.

2021-12-20 15:42 UTC, rochacbruno commented on .github/workflows/ci.yml
> -          PY_COLORS: '1'
https://github.com/jctanner/galaxy_ng/blob/SKIP_DEPENDABOT/.github/workflows/ci.yml#L1-L6

2021-12-20 15:42 UTC, rochacbruno commented on .github/workflows/ci.yml
> +          GITHUB_USER: ${{ github.event.pull_request.user.login }}
we can add more vars in 2 ways

1. https://github.com/ansible/galaxy_ng/blob/master/template_config.yml#L26 adding as a config param
2. add as part of template https://github.com/pulp/plugin_template/blob/master/templates/macros.j2#L1-L18

2021-12-20 16:29 UTC, awcrosby commented
/retest

2021-12-20 19:18 UTC, awcrosby submitted a review, later dismissed

2021-12-20 20:23 UTC, awcrosby commented on .ci/scripts/validate_commit_message_custom.py
> +    github_user = os.environ.get("GITHUB_USER")
where will `GITHUB_USER` get into the environment?

2021-12-20 20:24 UTC, awcrosby reviewed
where will `GITHUB_USER` from `validate_commit_message_custom.py` get into the environment?

2021-12-20 21:07 UTC, rochacbruno commented
looks like there is a GITHUB_ACTOR added by default https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

2021-12-21 16:20 UTC, rochacbruno approved these changes
not sure about the source of GITHUB_USER var, everything else LGTM

2022-01-04 05:52 UTC, himdel commented
> not sure about the source of GITHUB_USER var

For UI, that's https://github.com/ansible/ansible-hub-ui/pull/1380/files#diff-1da7a27709d11ac16eef3de8e46ed10672b7b1d63a790ffbcbd23a94b19efdcbR22

Though maybe we should provide the env var in galaxy_ng as well? (We're probably not using patchback here, but dependabot yes.)

2022-01-04 16:02 UTC, jctanner commented
@himdel alterting the workflow file in this repo would require an edit to https://github.com/ansible/galaxy_ng/blob/master/template_config.yml#L26  and then a regeneration with https://github.com/pulp/plugin_template which would add the env var to *every* task in the workflow file. I'd rather not have to deal with that right now.

2022-01-04 18:44 UTC, himdel commented
> I'd rather not have to deal with that right now.

Understood, yeah it's a bit too complicated now :)
I'm fine with galaxy_ng not providing any usenames, seems like we don't *need* to for now :+1:

2022-01-04 22:22 UTC, merged