Allow set of GALAXY_MINIMUM_PASSWORD_LENGTH for AUTH_PASSWORD_VALIDATORS
ansible/galaxy_ng pull request #1253
Opened 2022-05-05 15:00 UTC by rochacbruno

Issue: AAH-1531

Allow set of GALAXY_MINIMUM_PASSWORD_LENGTH for AUTH_PASSWORD_VALIDATORS

# Description 🛠
_Add PR description here_

# Reviewer Checklists  👀
Developer reviewer:
- [ ] Code looks sound, good architectural decisions, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-know-about-code-smells/)
- [ ] There is a Jira issue associated (note that "No-Issue" should be rarely used)
- [ ] Tests are included in `galaxy_ng/tests/integration` or `galaxy_ng/tests/functional`, and they fully cover necessary test scenarios… or tests not needed

QE reviewer ([exceptions](https://docs.engineering.redhat.com/display/AUTOHUB/Other+Team+Processes#OtherTeamProcesses-galaxy_ngrepo)):
- [ ] Tests are included in `galaxy_ng/tests/integration` or `galaxy_ng/tests/functional`, and they fully cover necessary test scenarios… or tests not needed
- [ ] PR meets applicable Acceptance Criteria for associated Jira issue

Note: when merging, include the Jira issue link in the squashed commit

2022-05-05 22:39 UTC, rochacbruno commented
/retest

2022-05-06 13:30 UTC, newswangerd approved these changes

2022-05-06 13:51 UTC, ironfroggy requested changes
We will need to file an AAP ticket for the installer to expose this to users.

Does this need any backports?

2022-05-06 13:51 UTC, ironfroggy commented on .compose.env.example
> +## Customize password lenght validation
typo here with "lenght"

2022-05-06 13:51 UTC, ironfroggy commented on docs/config/user_access.md
> +export PULP_PULP_GALAXY_MINIMUM_PASSWORD_LENGTH=15
Is this correct with the double prefix?

2022-05-06 15:30 UTC, rochacbruno commented
/retest

2022-05-06 16:35 UTC, rochacbruno commented
/retest

2022-05-10 15:07 UTC, jctanner requested changes
Please add at least one test.

2022-05-11 13:47 UTC, jctanner approved these changes
:+1:

2022-05-12 13:55 UTC, ironfroggy approved these changes

2022-05-12 17:33 UTC, merged