RBAC Roles
ansible/galaxy_ng pull request #1270
Opened 2022-05-16 18:33 UTC by newswangerd

This is a mega PR to merge all of the work that has been done in the `feature/rbac-roles` branch.

2022-07-20 14:23 UTC, alikins requested changes
Mostly small stuff, but a few things that I'd like to see. The stuff that can be split into a smaller PR for example.

2022-07-20 14:23 UTC, alikins commented on galaxy_ng/app/tasks/registry_sync.py
> +            "signed_only": False,
Not sure I understand how this is related to RBAC?

2022-07-20 14:23 UTC, alikins commented on galaxy_ng/app/migrations/0028_move_perms_to_roles.py
> +      permission to it to make up for each missing permission.
This file needs some whitespace cleanup.

2022-07-20 14:23 UTC, alikins commented on galaxy_ng/tests/unit/migrations/test_0028_move_perms_to_roles.py
> +
Some whitespace cleanup needed here.

2022-07-20 14:23 UTC, alikins commented on requirements/requirements.common.txt
>  django-ipware==3.0.7
(compliment) A++ :100: Nice to see some deps go away. Nice Work.

2022-07-20 14:23 UTC, alikins commented on setup.py
> +
Looks very useful. But it could probably be split into it's own PR.

2022-07-20 14:23 UTC, alikins commented on template_config.yml
> +
Trailing newline needs cleanup

2022-08-08 16:34 UTC, newswangerd commented on .github/stale.yml
> +# Configuration for probot-stale - https://github.com/probot/stale
this came with the plugin template

2022-08-08 16:34 UTC, newswangerd commented on .github/workflows/scripts/before_install.sh
> +git fetch --depth=1 origin 20bec438da54ddd6da4102f046f12c9f796a2ce9
plugin template updates

2022-08-08 16:34 UTC, newswangerd commented on .github/stale.yml
> +# Configuration for probot-stale - https://github.com/probot/stale
plugin template updates

2022-08-08 16:34 UTC, newswangerd commented on .github/stale.yml
> +# Configuration for probot-stale - https://github.com/probot/stale
plugin template updates

2022-08-10 16:18 UTC, newswangerd commented on galaxy_ng/app/api/urls.py
> +         kwargs={"reverse_url_name": "galaxy:api:v3:content-root"}),
i think this has to do with upgrading pulp

2022-08-10 17:08 UTC, awcrosby approved these changes

2022-08-15 13:43 UTC, newswangerd commented
Moved to #1413 since the PR check seems to be permanently broken here.

2022-08-15 13:43 UTC, closed without merging