Update The Filter For Red Hat Index of EE
ansible/galaxy_ng pull request #1328
Opened 2022-06-23 18:04 UTC by timway

#### What is this PR doing:
The category is called "Automation execution environment" as of this commit. Without this change the task completes without any issue but does not return any data.

[Currently - Automation Execution Environment](https://catalog.redhat.com/api/containers/v1/repositories?filter=build_categories=in=(%27Automation%20Execution%20Environment%27))
vs
[Modified - Automation execution environment](https://catalog.redhat.com/api/containers/v1/repositories?filter=build_categories=in=(%27Automation%20execution%20environment%27))

Issue: AAH-1737

#### Notes: 

**PR Author**: Add a QE reviewer ([exceptions](https://docs.engineering.redhat.com/display/AUTOHUB/Other+Team+Processes#OtherTeamProcesses-galaxy_ngrepo)); 
**Reviewers**: look for sound code, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-know-about-code-smells/), docs & test coverage
**Merger**: When merging, include the Jira issue link in the squashed commit

2022-06-24 13:33 UTC, newswangerd commented
@timway can you update this pr to inlcude `No-Issue` in the commit message, so that CI passes?

2022-06-24 13:34 UTC, rochacbruno requested changes
- Commits must be signed
- add a `CHANGES/1737.bugfix` with one liner describing the change
- We are requiring tests for every commit (however we do not have tests for execution environments yet so @newswangerd can give a hint on what/where to test)

2022-06-24 13:40 UTC, newswangerd commented
@timway also need to add `Issue: AAH-1737` to the commit message so that CI passes.

2022-07-06 16:40 UTC, newswangerd commented
Reopening this here: https://github.com/ansible/galaxy_ng/pull/1346

2022-07-06 16:40 UTC, closed without merging