[stable-4.5] Update pulp container to 2.10.7
ansible/galaxy_ng pull request #1429
Opened 2022-08-23 20:44 UTC by newswangerd

No-Issue

#### What is this PR doing:

Issue: AAH-####

#### Reviewers must know:

#### Notes: 

**PR Author**: Add a QE reviewer ([exceptions](https://docs.engineering.redhat.com/display/AUTOHUB/Other+Team+Processes#OtherTeamProcesses-galaxy_ngrepo)); 
**Reviewers**: look for sound code, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-know-about-code-smells/), docs & test coverage
**Merger**: When merging, include the Jira issue link in the squashed commit

2022-08-23 22:13 UTC, awcrosby requested changes

2022-08-23 22:13 UTC, awcrosby commented on CHANGES.rst
> +4.5.2 (2022-05-04)
not sure if this was an add from towncrier or manual, but it looks like this should be 4.5.0
```suggestion
4.5.0 (2022-05-04)
```

2022-08-23 22:16 UTC, awcrosby approved these changes

2022-08-24 13:28 UTC, ironfroggy approved these changes

2022-08-24 14:36 UTC, merged