Update access policies for ansible repository management
ansible/galaxy_ng pull request #1530
Opened 2022-11-08 14:11 UTC by jerabekjiri

#### What is this PR doing:

Issues: [AAH-2001](https://issues.redhat.com/browse/AAH-2001), [AAH-2002](https://issues.redhat.com/browse/AAH-2002), [AAH-2003](https://issues.redhat.com/browse/AAH-2003)

#### Reviewers must know:

**PR Author & Reviewers**: Keep or remove backport labels per [Backporting Guidelines](https://github.com/ansible/galaxy_ng/wiki/Backporting-Guidelines)
**Reviewers**: Look for sound code, no [code smells](https://www.codegrip.tech/productivity/everything-you-need-to-know-about-code-smells/), docs & test coverage
**Merger**: When merging, include the Jira issue link in the squashed commit

2022-11-15 13:44 UTC, newswangerd approved these changes

2022-12-08 13:56 UTC, newswangerd requested changes
Please add tests to https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/tests/integration/api/test_rbac_roles.py to verify that users with the roles you updated have permissions to create, update and delete remotes, repositories and distributions.

2022-12-08 19:24 UTC, bmclaughlin reviewed
LGTM pending David's requested changes.

2022-12-22 13:56 UTC, newswangerd approved these changes

2022-12-22 13:57 UTC, merged