Import iqe rbac tests
ansible/galaxy_ng pull request #1543
Opened 2022-11-17 09:20 UTC by chr-stian

Issue: AAH-2033

Import [RBAC tests from IQE repo](https://gitlab.cee.redhat.com/insights-qe/iqe-automation-hub-plugin/-/blob/master/iqe_automation_hub/tests/api/test_rbac.py). 

And some required tools too.
They are marked with this decorator `@pytest.mark.min_hub_version("4.6dev")` so that they get skipped if hub version is lower than 4.6

2022-11-22 15:31 UTC, chr-stian commented
/retest

2022-11-22 20:09 UTC, awcrosby requested changes
pr-check.sh failure

2022-11-22 20:09 UTC, awcrosby commented on galaxy_ng/tests/integration/utils/iqe_utils.py
> +            g_client = GalaxyClient(
It looks like this call to galaxykit is causing the pr-check.sh to fail with `KeyError: 'access_token'`

2022-11-29 21:01 UTC, awcrosby commented
The workflow `Standalone / integration` goes from 21min to 33min with this change. Maybe they should be in their own workflow with their own pytest mark (similar to https://github.com/ansible/galaxy_ng/blob/master/.github/workflows/ci_standalone-rbac-roles.yml and the `rbac_roles` mark). @chr-stian what do you think?

2022-12-01 11:10 UTC, chr-stian commented
> The workflow `Standalone / integration` goes from 21min to 33min with this change. Maybe they should be in their own workflow with their own pytest mark (similar to https://github.com/ansible/galaxy_ng/blob/master/.github/workflows/ci_standalone-rbac-roles.yml and the `rbac_roles` mark). @chr-stian what do you think?

Done

2022-12-01 22:23 UTC, awcrosby approved these changes

2022-12-02 15:33 UTC, jctanner commented
replaced by https://github.com/ansible/galaxy_ng/pull/1560

2022-12-02 15:33 UTC, closed without merging