Ensure repo deletion also removes associated content and artifacts
ansible/galaxy_ng pull request #1603
Opened 2023-01-30 16:52 UTC by ShaiahWren

Issue: AAH-2024

Prior to the pr, the `delete_container_distribution` method deleted the repo from the system, yet the associated content and artifacts remained. 

To ensure all content is deleted, the content_pks in orphan cleanup for the method is set to the content pks for the given repository, and the protection time, set to 0.

1. Grab the repo ids through list comprehension of the instance_ids passed into the deletion method
2. Query objects in the RepositoryContent model and filter out the content pks associated with those repo ids. ( RepositoryContent.objects.filter(repository__pk__in = repo ids).values_list("content_pks"). 
3. Assign that list of content pks to the content pks field for orphan cleanup, and set the orphaned protection time to 0. 

That should be it!

2023-02-07 15:03 UTC, newswangerd commented on galaxy_ng/app/tasks/deletion.py
> +    repository_content_pks = \
This isn't working and I can't figure out why. When I add `print(repository_content_pks)`, I get `<QuerySet []>` which is wrong. It shouldn't be empty.

2023-02-07 15:30 UTC, newswangerd commented on galaxy_ng/app/tasks/deletion.py
> +        RepositoryContent.objects.filter(repository__pk__in=repository_ids)\
This also needs to exclude content that is in other repositories. I _think_ this should work, but you'll need to test it.

```
RepositoryContent.objects.annotate(num_repos=Count("repository")).filter(repository__pk__in=repository_ids, num_repos=1)
```

2023-02-07 15:34 UTC, newswangerd commented on galaxy_ng/tests/integration/api/test_container_delete.py
> +    assert len(task.created_resources) == 1
why are you checking that created resource is 1?

2023-02-15 14:23 UTC, newswangerd requested changes
Your tests are still failing.

```
         # Delete repository, contents, and artifacts for alpine1, NOT alpine2
        delete_response = client(f"{api_prefix}/v3/"
                                 "plugin/execution-environments/repositories/alpine1/", method='DELETE')
        resp = wait_for_task(client, delete_response, timeout=10000)
        assert resp["state"] == "completed"
    
        # Ensure content hrefs from alpine1 still exists
        content_hrefs = [item["pulp_href"] for item in content_list_1["results"]]
    
        for item in content_hrefs:
            success = None
            try:
                client(f"{api_prefix}{item}")
                success = True
            except GalaxyError as ge:
                if ge.http_code in [403, 404]:
                    success = False
                else:
                    raise Exception(ge)
    
>           assert success
E           assert False
```

2023-02-15 22:23 UTC, ShaiahWren commented
@newswangerd the first test does pass according to github, it's the second that doesn't - and from the output on github it seems like an issue with push to registry. Why is there a line that says "assert False" at the bottom of the file... is that an output of the test ran locally? (None of my container tests run locally, properly...)

```The push refers to repository [localhost:5001/alpine1]
7cd52847ad77: Preparing
7cd52847ad77: Pushed
latest: digest: sha256:e2e16842c9b54d985bf1ef9242a313f36b856181f188de21313820e177002501 size: 528
The push refers to repository [localhost:5001/alpine2]
7cd52847ad77: Preparing
7cd52847ad77: Mounted from alpine1
latest: digest: sha[256](https://github.com/ansible/galaxy_ng/actions/runs/4166837580/jobs/7211678024#step:14:257):e2e16842c9b54d985bf1ef9242a313f36b856181f188de21313820e177002501 size: 528
FAILED
'''

2023-02-16 13:58 UTC, newswangerd commented
@ShaiahWren it says `assert False` because `False` is the value of the `success` variable

2023-02-16 20:18 UTC, newswangerd commented on galaxy_ng/tests/integration/api/test_container_delete.py
> +    repo_href_1 = (distro_response1["results"][0]["repository"]).replace("/api/automation-hub", "")
You shouldn't have to replace `/api/automation-hub`. The href it gives you will work by itself

2023-02-17 18:26 UTC, jerabekjiri commented
@ShaiahWren if you rebase, this `test_openapi.py::test_galaxy_openapi_validation`  should get fixed

2023-02-17 18:36 UTC, jerabekjiri commented on galaxy_ng/tests/integration/api/test_container_delete.py
> +            client(f"{api_prefix}{item}")
`item` is `pulp_href` and already contains full path to the content (`/api/automation-hub/pulp/api/v3/content/container/tags/9723d20f-9095-4f0c-9b5e-bcbafe387cfc/`)
```suggestion
            client(item)
```

2023-02-28 15:31 UTC, newswangerd approved these changes

2023-02-28 15:31 UTC, merged