Fix err 500 on listing /api/v1/namespaces with browsable api enabled
ansible/galaxy_ng pull request #1915
Opened 2023-10-03 16:14 UTC by jerabekjiri

Issue: AAH-2733

This feels like a hacky fix. I'm not sure why django says the method is POST on visiting the endpoint if browsable api is enabled. 
(if `?format=json`, endpoint works correctly even user is logged in)
Still investigating.

2023-10-11 14:29 UTC, jerabekjiri commented
@drodowic Is it okay to use the `PULP_CONTENT_ORIGIN` variable to enable the `CustomBrowsableAPIRenderer` renderer class only for galaxy.ansible.com (and also for dev and stage)? I don't think I have any other way to test this.

2023-10-12 15:24 UTC, drodowic commented
> @drodowic Is it okay to use the `PULP_CONTENT_ORIGIN` variable to enable the `CustomBrowsableAPIRenderer` renderer class only for galaxy.ansible.com (and also for dev and stage)? I don't think I have any other way to test this.

PULP_CONTENT_ORIGIN is explicitly set in each environment for galaxy.ansible.com so yes I think it's unique enough to use in this case.

2023-10-12 17:33 UTC, drodowic approved these changes

2023-10-13 15:06 UTC, rochacbruno requested changes

2023-10-13 15:06 UTC, rochacbruno commented on galaxy_ng/app/dynaconf_hooks.py
> +    }
There is no need to use dynaconf_hooks to set default values without any conditional, the hooks are valuable when the return dict to be merged with settings can vary depending on a condition.

The reason to perform the conditional here is that the hooks file runs at the very late stage of settings building, if the conditional is performed inside the `settings.py` the state of `settings` objects is unfinished, for example, another plugin can set a variable to override it.

```suggestion
import re

def configure_renderers(settings) -> Dict[str, Any]:
    "Set renderer classes conditionaly."
    if re.search(
        r'galaxy(-dev|-stage)*.ansible.com', settings.get('CONTENT_ORIGIN', "")
    ):
        # overrride the `REST_FRAMEWORK__DEFAULT_RENDERER_CLASSES`
        return {
            "REST_FRAMEWORK__DEFAULT_RENDERER_CLASSES": [
                'galaxy_ng.app.renderers.CustomBrowsableAPIRenderer'
            ]
        }
        
    return {}   # do nothing
```

2023-10-16 11:34 UTC, jerabekjiri commented on docker/etc/settings.py
> +
@rochacbruno 
>  also, docker/etc/settings.py is only used by cloud deployment is that what you indend?


I want `CustomBrowsableAPIRenderer` to be used only in `galaxy.ansible.com` (and in the dev env as well), not in CRC for now.

2023-10-16 11:35 UTC, jerabekjiri commented on docker/etc/settings.py
> +
@rochacbruno 
>  also, docker/etc/settings.py is only used by cloud deployment is that what you indend?


I want `CustomBrowsableAPIRenderer` to be used only in `galaxy.ansible.com` (and in the dev env as well), not in CRC for now.

2023-10-17 23:05 UTC, jctanner commented
Does this problem exist on the devstack in a way that we could have reproduced it?

2023-10-18 12:17 UTC, jerabekjiri commented
@jctanner I can probably add test with `?format=api` to test the behavior.

2023-10-20 13:45 UTC, rochacbruno approved these changes

2023-10-23 10:34 UTC, merged