Adding support for galaxy operator
ansible/galaxy_ng pull request #2058
Opened 2024-02-02 22:37 UTC by aknochow

1. Updating api and worker entrypoint scripts to pre-create directories in /var/lib/pulp/ 
2. Adding skopeo dependency for content signing script 
3. Adding readyz.py and wait_on_postgres.py scripts for galaxy-operator healthchecks

depends-on: https://github.com/ansible/galaxy-operator/pull/17

2024-02-06 15:49 UTC, rooftopcellist requested changes

2024-02-06 15:53 UTC, aknochow commented on galaxy-operator/bin/wait_on_postgres.py
> +#!/usr/bin/env python3
done!

2024-02-06 20:56 UTC, drodowic approved these changes

2024-02-07 14:32 UTC, rooftopcellist commented on galaxy-operator/bin/readyz.py
> +gunicorn: master \[pulp-{content,api}\]
The CI linter is just complaining about the backslashes here in the docstring.

```
Run [ ! -x .ci/scripts/extra_linting.sh ] || .ci/scripts/extra_linting.sh
./galaxy-operator/bin/readyz.py:51:18: W605 invalid escape sequence '\['
./galaxy-operator/bin/readyz.py:51:38: W605 invalid escape sequence '\]'
```

We can just remove them imo.

2024-02-07 14:33 UTC, rooftopcellist approved these changes
This changeset looks good.  

Idea: I think we might want to think about adding a "configure-signing-services.sh" for the initContainer to use in a future PR to make the operator codebase a bit cleaner.  

But a PR for another day.

2024-02-08 23:02 UTC, rooftopcellist commented
@himdel @drodowic @jctanner It looks all of the CI issues pertaining to this PR have been fixed.  But the Galaxy CI checks are all failing due to an unrelated problem now when building the image:

```
    7.066 ERROR: Package 'galaxy-ng' requires a different Python: 3.8.17 not in '>=3.9'
    ------
    Containerfile:8
    --------------------
       6 |     # Install python packages
       7 |
       8 | >>> RUN pip3 install ./galaxy_ng
```

I see this in other PR's as well for example:
* https://github.com/ansible/galaxy_ng/pull/2066

Actually, it looks like this might just need a rebase to pick up this change:
* https://github.com/ansible/galaxy_ng/pull/2048/files#diff-a0aba5a2bd30b2f80a3a18aa24ce43670b1320ca0a8b9c103bb3bc971ae30a85R33

We'll try that, cc @aknochow

2024-02-08 23:33 UTC, rooftopcellist commented
It appears that the base image used by CI when building has python3.8.17, and python3.9+ is required.  

```
[chadams@awx galaxy_ng]$ docker run -it ghcr.io/pulp/pulp-ci-centos bash

[root@2bfd2acc2a67 /]# python3 --version
Python 3.8.17
```

2024-02-09 14:55 UTC, merged