Enhancement/remove ui non repo collection endpoint
ansible/galaxy_ng pull request #514
Opened 2020-10-12 16:35 UTC by awcrosby

Related-Issue: #AAH-47

These endpoints are no longer used by the UI and have references to
the certified flag which is being removed.

2020-10-12 18:05 UTC, newswangerd requested changes
This looks good, but it shouldn't be merged until after the next cloud release happens.

2020-10-13 13:46 UTC, awcrosby commented
@newswangerd I added back in the _ui/collections endpoint as deprecated and changed it to use the `published` repo so it can be removed after the UI deployment.

2020-10-14 15:12 UTC, alikins commented on galaxy_ng/app/api/ui/viewsets/collection.py
> +# TODO: Remove when ui is updated and no longer uses this endpoint
This is related to the cloud deploy stuff discussed yesterday?  ie, needing to have both versions of this endpoint running until there is no ui running that needs it?

2020-10-19 16:20 UTC, newswangerd approved these changes

2020-10-19 17:11 UTC, merged