Fix errors caused by #715
ansible/galaxy_ng pull request #721
Opened 2021-04-12 18:27 UTC by bmclaughlin

- Unbound variable errors reported on line 100
- TCP port localhost:6379 not available
Issue: AAH-486

2021-04-12 23:21 UTC, hendersonreed commented
This looks good to me, going to check out the fork and verify it works as expected.

2021-04-13 10:09 UTC, ZitaNemeckova commented
Works for me :)

2021-04-13 13:26 UTC, cutwater requested changes

2021-04-13 13:26 UTC, cutwater commented on docker/entrypoint.sh
> +    if [[ ${PULP_REDIS_PASSWORD:-nopassword} = "nopassword" ]]; then
```suggestion
    if [[ -z "${PULP_REDIS_PASSWORD:-}" ]]; then
```

2021-04-13 13:33 UTC, cutwater requested changes

2021-04-13 13:33 UTC, cutwater commented on docker/entrypoint.sh
> +    redis_connection_hack
you can move it below wait-for-tcp to avoid variable assignments

2021-04-13 14:03 UTC, cutwater approved these changes

2021-04-13 14:08 UTC, merged