Update Redis connection settings
ansible/galaxy_ng pull request #776
Opened 2021-05-21 18:14 UTC by bmclaughlin

Update to only populate PULP_REDIS_URL if the relevant PULP_REDIS_* environment variables are set.

Issue: AAH-581

2021-05-24 13:04 UTC, cutwater commented on docker/entrypoint.sh
> +    if [[ ! -z "${PULP_REDIS_HOST-}" && ! -z "${PULP_REDIS_PASSWORD-}" &&
```suggestion
    if [[ ! -z "${PULP_REDIS_HOST:-}" && ! -z "${PULP_REDIS_PASSWORD:-}" &&
```

2021-06-02 12:50 UTC, cutwater approved these changes
In bash you can check for non-empty string by using `-n`:

```
if [[ -n "${redis_host}" ...
```

Shouldn't it be OR condition?

2021-06-02 12:52 UTC, cutwater requested changes
See my comments above.

2021-06-02 13:01 UTC, cutwater commented on docker/entrypoint.sh
>      fi
```
redis_connection_hack() {
    redis_host="${PULP_REDIS_HOST:-}"
    redis_password="${PULP_REDIS_PASSWORD:-}"
    redis_port="${PULP_REDIS_PORT:-}"
    redis_ssl="${PULP_REDIS_SSL:-}"

    if [[ -z "${redis_host}" && -z "${redis_port}" 
          && -z "${redis_password}" && -z "${redis_ssl}" ]]; then
        return
    fi

    if [[ "${redis_ssl}" == "true" ]]; then
        protocol="rediss://"
    else
        protocol="redis://"
    fi

    PULP_REDIS_URL="${protocol}:${redis_password}@${redis_host:-localhost}:${redis_port:-6379}/0"
    unset PULP_REDIS_HOST PULP_REDIS_PORT PULP_REDIS_PASSWORD PULP_REDIS_SSL
    export PULP_REDIS_URL
}
```

2021-06-02 13:02 UTC, cutwater commented on docker/entrypoint.sh
> +        PULP_REDIS_URL="${protocol}:${password}@${redis_host}:${redis_port}/0"
Must be `redis_password`

2021-06-02 14:53 UTC, bmclaughlin commented
@cutwater, updated.  Successfully tested against dev environment and ephemeral templates.

2021-06-02 15:52 UTC, cutwater approved these changes
lgtm

2021-06-02 16:03 UTC, merged