Pin pulp-container
ansible/galaxy_ng pull request #777
Opened 2021-05-24 15:21 UTC by fao89

This is currently breaking pulp-operator
https://github.com/pulp/pulp-operator/runs/2652733659?check_suite_focus=true

pulp-container 2.6 requires pulpcore >=3.12.1
https://github.com/pulp/pulp_container/blob/2.6.0/requirements.txt

2021-05-25 14:24 UTC, rochacbruno commented on setup.py
> +    "click~=7.1.2",
```suggestion
    "click~=7.1.2",  # added as a workaround to fix rq, can be removed when pulpcore gets updated to 3.11.2
```

2021-05-25 14:35 UTC, newswangerd commented
We pinned click here: https://github.com/ansible/galaxy_ng/pull/774/files

Might need to rebase

2021-05-25 18:26 UTC, rochacbruno approved these changes

2021-05-26 16:01 UTC, alikins commented
Also needs requirements/*.txt updated.
ie, run

`PIP_COMPILE_UPDATE_SPEC='--upgrade-package "pulp-container>=2.5.2,<2.6.0"' make requirements`

2021-05-26 16:01 UTC, alikins requested changes
needs requirements.*.txt updated

2021-05-26 17:30 UTC, alikins approved these changes

2021-06-10 12:47 UTC, merged