Make synclist task with policy 'exclude' include all versions not just is_latest AAH-485
ansible/galaxy_ng pull request #783
Opened 2021-06-01 13:26 UTC by alikins

Intended fix for 'Syncing from synclist is pulling all content, ignoring sync toggles'

https://issues.redhat.com/browse/AAH-585?focusedCommentId=16232352&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16232352  goes into details about the root cause.

I think the synclist 'curate' is only removing the latest version of the collection from the synclist RepositoryVersion instead of all the versions when the synclist.policy=='exclude'.

This pr is a WIP that sets `is_highest=False` for exclude case.

Issue: AAH-485

2021-07-19 16:34 UTC, rochacbruno requested changes
pending also a rebase

2021-07-19 16:34 UTC, rochacbruno commented on galaxy_ng/app/tasks/synclist.py
> +    log.debug('task_kwargs: %s', pprint.pformat(task_kwargs))
do we pprint our log output? `pformat` generates indentation and I think we need to keep log (when output is a file) in to single lines and let formatting to the handlers and/or reader.

2021-07-19 16:34 UTC, rochacbruno commented on galaxy_ng/app/tasks/synclist.py
> +            is_highest=is_highest,
what if here you use

```py
is_highest=synclist.policy != "exclude"
```

and remove the `if` block above

2021-07-19 16:34 UTC, rochacbruno commented on CHANGES/585.bugfix
> +Resolve issues syncing all content via synclist
this CHANGELOG must be a single line now

2021-07-19 16:35 UTC, rochacbruno commented on galaxy_ng/app/tasks/synclist.py
> +        is_highest = False
This whole block is not needed because `synclist.policy == 'exclude'` already evaluates to a boolean

2021-07-20 18:13 UTC, rochacbruno approved these changes

2021-07-20 18:18 UTC, rochacbruno commented on galaxy_ng/app/tasks/synclist.py
> +    is_highest_query_param = {}
Explanation for reviewers:

When policy is `exclude` this is going to be an empty dict,so the expansion later will make the query `Q(` to not filter by version including on the queryset all the versions of the collection.

When it is `include` then `is_highest = True` is added to the query, to it filters only the latest version of a collection.

2021-07-20 19:05 UTC, awcrosby approved these changes

2021-07-21 15:06 UTC, newswangerd approved these changes

2021-07-21 16:10 UTC, merged