[PoC] Enable keycloak SSO for podman login
ansible/galaxy_ng pull request #949
Opened 2021-09-09 22:17 UTC by newswangerd

This creates a new pulp container token endpoint for generating container JWT access tokens. It uses a new authentication class that mimics the behavior of Basic Auth, but performs authentication against keycloak instead of the Django user model.

Note, for this to work, Direct Access Grants must be enabled in keycloak.

Tod:
- [ ] automate keycloak configuration
- [ ] figure out how to validate jwt token

Keycloak config:

![Screen Shot 2021-09-09 at 6 02 09 PM](https://user-images.githubusercontent.com/6063371/132768824-0ace13fd-d92f-4020-b7f2-bfc1ee24a306.png)
![Screen Shot 2021-09-09 at 6 02 16 PM](https://user-images.githubusercontent.com/6063371/132768826-260fb26b-2a1c-4951-8359-9e2bba6e2e24.png)

2021-09-09 22:19 UTC, newswangerd commented
@chambridge how do I automate the keycloak setup to enable Direct Access Grants?

2021-09-09 23:04 UTC, chambridge commented
> @chambridge how do I automate the keycloak setup to enable Direct Access Grants?

Pretty simple: https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_client_module.html#parameter-direct_access_grants_enabled

Would just update here (https://github.com/ansible/galaxy_ng/blob/master/dev/standalone-keycloak/keycloak-playbook.yaml#L55) with `yes`

2021-09-10 14:12 UTC, rochacbruno commented on galaxy_ng/app/settings.py
> +    ]
when/if #945 is merged, this settings is moved to dynaconf_hooks.py file https://github.com/ansible/galaxy_ng/pull/945/files#diff-51ac604a5e6e00d70270d768fd15bb83bca7f1d919f0471e0f43df8baba9d059R84

2021-09-10 14:18 UTC, ipanova commented on galaxy_ng/app/auth/keycloak.py
> +            # If keycloak basic auth fails, try regular basic auth.
:+1:

2021-09-10 14:44 UTC, newswangerd commented
/retest

2021-09-10 16:22 UTC, rochacbruno requested changes

2021-09-10 16:22 UTC, rochacbruno commented on galaxy_ng/app/settings.py
> +    ]
@newswangerd move this to galaxy_ng/app/dynaconf_hooks.py https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/app/dynaconf_hooks.py#L84

there you add it to a dictionary
```py
data["REST_FRAMEWORK__DEFAULT_AUTHENTICATION_CLASSES"] = [
    "rest_framework.authentication.SessionAuthentication",
    "galaxy_ng.app.auth.keycloak.KeycloakBasicAuth",
]
```

2021-09-10 17:39 UTC, rochacbruno approved these changes

2021-09-10 18:20 UTC, merged